<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>e9c0a1f0-822f-4184-9046-0735127c9b78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[8]/div/div/div/div/div/div/div/div[2]/div/div/a/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>306099f5-5b44-49ae-b865-3a0fa4fb5189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>8521fc52-878b-4a6e-91db-5506f757ff41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[8]/div[@class=&quot;lazyload-1 lazyloaded&quot;]/div[@class=&quot;pagebuilder-column-group&quot;]/div[@class=&quot;pagebuilder-column-line&quot;]/div[@class=&quot;pagebuilder-column lazyloaded&quot;]/div[@class=&quot;pagebuilder-slider brand-slider height-65e1672d74d69 slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active&quot;]/div[1]/div[1]/a[1]/div[@class=&quot;pagebuilder-slide-wrapper lazyloaded&quot;]/div[@class=&quot;pagebuilder-overlay pagebuilder-poster-overlay&quot;]/div[@class=&quot;pagebuilder-poster-content&quot;]/div[1]</value>
      <webElementGuid>3938cf1b-5656-4fb9-97b5-96813bd875fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[8]/div/div/div/div/div/div/div/div[2]/div/div/a/div/div/div/div</value>
      <webElementGuid>1e2567ec-141c-4fe6-8cd1-b911b231c7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/div/div/div[2]/div/div/a/div/div/div/div</value>
      <webElementGuid>2204bf10-9507-45e1-bc5d-9cc865879cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
