<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>aKeranjang</name>
   <tag></tag>
   <elementGuidId>404d6a27-2c1b-44df-89ba-c467dbbf42d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;document.getElementsByClassName('klevu-fluid')[0].style.display = 'none'&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.action.showcart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>61debcf4-ae52-414c-a7d0-e0a8be47fad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action showcart</value>
      <webElementGuid>7ca1e902-5290-45a3-aac1-bbfd0c6dcce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementsByClassName('klevu-fluid')[0].style.display = 'none'</value>
      <webElementGuid>8c2abf57-40a1-4e0d-96c1-2a101e836c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.matahari.com/checkout/cart/</value>
      <webElementGuid>de38cccf-6dca-4f11-9f19-3c0932ae4ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>scope: 'minicart_content'</value>
      <webElementGuid>d9e3d359-370e-4fe7-9209-e752e072780d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keranjang 1 1items</value>
      <webElementGuid>c474d55b-aee4-4389-af51-5abba762af31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;html-body&quot;)/div[@class=&quot;page-wrapper&quot;]/header[@class=&quot;page-header&quot;]/div[@class=&quot;header content&quot;]/div[@class=&quot;minicart-wrapper&quot;]/a[@class=&quot;action showcart&quot;]</value>
      <webElementGuid>38b91a56-01ff-483c-a63f-a22ebe644212</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;document.getElementsByClassName('klevu-fluid')[0].style.display = 'none'&quot;]</value>
      <webElementGuid>0c6d4fed-f686-4e69-a251-9bccdc4222b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='html-body']/div[3]/header/div[2]/div/a</value>
      <webElementGuid>badee2aa-8f60-4e35-8245-c685b12db58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Nav'])[1]/following::a[2]</value>
      <webElementGuid>c1fe27a4-4faa-495a-ad74-b67bd854411d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belanja 299rb bisa dapat Gratis Ongkir sampai 10 September 2023!'])[1]/following::a[2]</value>
      <webElementGuid>427b9e78-7571-4a77-be81-29f75cfb8c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.matahari.com/checkout/cart/')]</value>
      <webElementGuid>d4d351ba-1acb-4ec3-af0c-4983c68d8084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>b0a1e408-21e6-49d9-9337-e559f8e55c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.matahari.com/checkout/cart/' and (text() = 'Keranjang 1 1items' or . = 'Keranjang 1 1items')]</value>
      <webElementGuid>5c79f9dd-203d-46cd-8c6f-191731fe32c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
