<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div24-36</name>
   <tag></tag>
   <elementGuidId>9437b65f-3f95-4800-8c1b-b116507d4137</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id, 'option-label-size-558-item-')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;product-options-wrapper&quot;)/div[@class=&quot;fieldset&quot;]/div[@class=&quot;product-item__swatches-container&quot;]/div[@class=&quot;swatch-opt-1077264&quot;]/div[@class=&quot;swatch-attribute size&quot;]/div[@class=&quot;cart-popup-swatch-attribute-options clearfix&quot;]/div[@id=&quot;option-label-size-558-item-20583&quot;][count(. | //*[@id = 'option-label-size-558-item-20583' and (text() = '24-36' or . = '24-36')]) = count(//*[@id = 'option-label-size-558-item-20583' and (text() = '24-36' or . = '24-36')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cart-popup-swatch-attribute-options.clearfix > #option-label-size-558-item-20583</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a48708ce-0690-4f66-ac15-1d1b91afa66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-option text</value>
      <webElementGuid>f6e04589-01ed-441c-8d3b-29e44f384c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-label-size-558-item-20583</value>
      <webElementGuid>67693ef3-72f7-4991-973d-1f98e4b7063c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e08719e9-09a0-4db6-855b-a1d6cbe142a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d6631fb-4038-4276-a75d-e4e7b0f7a6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>option-label-size-558</value>
      <webElementGuid>9430a8ef-ce86-4a13-9db7-e032522405d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>41d88c45-3a21-458c-bc66-aca411809385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>22ecc6af-0d0c-4e6b-828b-d60a0857efad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-id</name>
      <type>Main</type>
      <value>20583</value>
      <webElementGuid>3d6495f7-06de-4a0d-883c-45966b56818c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-label</name>
      <type>Main</type>
      <value>24-36</value>
      <webElementGuid>17c89827-a26c-4d40-aa6a-40829830ca7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>24-36</value>
      <webElementGuid>5e9bf9bd-01ce-434b-bc1a-3cb26defb63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f1ae5223-1c80-42e6-aab5-e0215beef46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thumb-width</name>
      <type>Main</type>
      <value>110</value>
      <webElementGuid>9c889383-653f-42a3-baf7-c41238c85fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thumb-height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>6c0111de-d008-4fd5-9bed-169c6eaf5d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-tooltip-value</name>
      <type>Main</type>
      <value>24-36</value>
      <webElementGuid>26a4e1fc-8f7a-4a27-bd42-d16b22c003cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24-36</value>
      <webElementGuid>03332e4b-0dce-488b-b345-553de5010340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-options-wrapper&quot;)/div[@class=&quot;fieldset&quot;]/div[@class=&quot;product-item__swatches-container&quot;]/div[@class=&quot;swatch-opt-1077264&quot;]/div[@class=&quot;swatch-attribute size&quot;]/div[@class=&quot;cart-popup-swatch-attribute-options clearfix&quot;]/div[@id=&quot;option-label-size-558-item-20583&quot;]</value>
      <webElementGuid>0c1d2d51-4da1-4d65-9698-00074fd05fce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='option-label-size-558-item-20583'])[3]</value>
      <webElementGuid>2f305680-2096-4d2d-9c08-ca5d23db2077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-options-wrapper']/div/div/div/div/div/div</value>
      <webElementGuid>d0a7351d-dbd6-48a1-a056-0a60e2cd0959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ukuran'])[3]/following::div[2]</value>
      <webElementGuid>7f5c3916-9cbd-4b19-abb8-671086074b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 219,900'])[3]/following::div[7]</value>
      <webElementGuid>b832cd22-2de9-4c26-84fa-96aa0dedd2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warna'])[3]/preceding::div[4]</value>
      <webElementGuid>c45d30a9-997b-4e79-aad2-a82369bc87dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PASTEL PINK'])[1]/preceding::div[4]</value>
      <webElementGuid>f38af672-3348-43d3-bee5-d1535597721e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div</value>
      <webElementGuid>b23ee85a-bad1-4722-86e3-180c133dc95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'option-label-size-558-item-20583' and (text() = '24-36' or . = '24-36')]</value>
      <webElementGuid>b46cd9f4-5782-4229-aa2d-3ccd286dd259</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
